### DISCUSSION TITLE
detect/swin_t.yaml

### DISCUSSION THREAD

**Discussion by github-actions** [Y-T-G/community#30] [General]
# Discussion for `detect/swin_t.yaml`

## 📊 Metadata
👤 **author:** **@Y-T-G**
🎯 **task:** detect
🔑 **keywords:** `transformer`, `swin`
📝 **description:** Swin-T pretrained backbone with Detect head.
⚡ **flops:** 64.8
🔢 **parameters:** 31,736,461
💻 **min_version:** 8.3.64

If you found this config helpful, consider upvoting this discussion! 🔼

**Comment by pawara101** [comment]
hi @Y-T-G I used below config, but it sends me below error.
```yaml
nc: 12  # number of classes

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, TorchVision, [256, swin_t, DEFAULT, True, 5, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```

Error message
`RuntimeError: Given groups=1, weight of size [96, 3, 4, 4], expected input[1, 256, 32, 32] to have 3 channels, but got 256 channels instead`

Can you help me with this ?
